name = "RationalGenerators"
uuid = "2737ff73-0d59-47a5-9105-cfa0dee446ca"
authors = ["Ed Scheinerman <ers@jhu.edu>"]
version = "0.1.2"

[deps]
Primes = "27ebfcd6-29c5-5fa9-bf4b-fb8fc14df3ae"

[compat]
julia = "1"
Primes = "0.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
